apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: sa-reader
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sa-reader
  namespace: roboshop
subjects:
- kind: ServiceAccount
  name: roboshop-mysql-secret
  namespace: roboshop
roleRef:
  kind: Role
  name: sa-reader
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: Pod
metadata:
  name: sa-reader
  namespace: roboshop
spec:
  serviceAccountName: roboshop-mysql-secret
  containers:
  - name: amazon
    image: amazon/aws-cli
    command: ["sleep","100000"]